# Generated by Django 5.2.5 on 2025-08-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='报告编号')),
                ('report_type', models.CharField(choices=[('dryfilm', '干膜产品检测报告'), ('adhesive', '胶粘剂产品检测报告')], max_length=20, verbose_name='报告类型')),
                ('product_code', models.CharField(max_length=50, verbose_name='产品牌号')),
                ('batch_number', models.CharField(max_length=50, verbose_name='产品批号')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('inspector', models.CharField(max_length=50, verbose_name='检验人')),
                ('reviewer', models.CharField(blank=True, max_length=50, verbose_name='审核人')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='报告日期')),
                ('selected_items', models.JSONField(default=list, verbose_name='选择的检测项目')),
                ('test_results', models.JSONField(default=list, verbose_name='检测结果')),
                ('conclusion', models.CharField(blank=True, max_length=100, verbose_name='判定结论')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('inspector_signature', models.CharField(blank=True, max_length=100, verbose_name='检验人签名')),
                ('reviewer_signature', models.CharField(blank=True, max_length=100, verbose_name='审核人签名')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='审核日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='报告状态')),
            ],
            options={
                'verbose_name': '检测报告',
                'verbose_name_plural': '检测报告',
                'ordering': ['-report_date', '-report_number'],
            },
        ),
    ]
