# Generated by Django 5.2.5 on 2025-08-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='原料名称')),
                ('material_batch', models.CharField(max_length=50, unique=True, verbose_name='原料批号')),
                ('inspector', models.CharField(max_length=50, verbose_name='检测人')),
                ('sample_category', models.CharField(choices=[('单批样', '单批样'), ('装车样', '装车样'), ('掺桶样', '掺桶样')], max_length=50, verbose_name='样品类别')),
                ('test_date', models.DateField(verbose_name='测试日期')),
                ('supplier', models.CharField(max_length=100, verbose_name='供应商')),
                ('distributor', models.CharField(blank=True, max_length=100, verbose_name='经销商')),
                ('acceptance_form', models.CharField(blank=True, max_length=100, verbose_name='验收单号')),
                ('logistics_form', models.CharField(blank=True, max_length=100, verbose_name='物流单号')),
                ('coa_number', models.CharField(blank=True, max_length=100, verbose_name='COA编号')),
                ('final_judgment', models.CharField(blank=True, max_length=20, verbose_name='判定结果')),
                ('judgment_status', models.CharField(choices=[('待判定', '待判定'), ('合格', '合格'), ('不合格', '不合格'), ('待复检', '待复检')], default='待判定', max_length=20, verbose_name='判定状态')),
                ('judgment_details', models.JSONField(blank=True, default=dict, verbose_name='判定详情')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('appearance', models.CharField(blank=True, max_length=100, verbose_name='外观')),
                ('purity', models.FloatField(blank=True, null=True, verbose_name='纯度')),
                ('peak_position', models.FloatField(blank=True, null=True, verbose_name='出峰位置')),
                ('inhibitor_content', models.FloatField(blank=True, null=True, verbose_name='阻聚剂含量')),
                ('moisture_content', models.FloatField(blank=True, null=True, verbose_name='水分含量')),
                ('color', models.FloatField(blank=True, null=True, verbose_name='色度')),
                ('ethanol_content', models.FloatField(blank=True, null=True, verbose_name='乙醇含量')),
                ('acidity', models.FloatField(blank=True, null=True, verbose_name='酸度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('modified_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('modification_reason', models.TextField(blank=True, verbose_name='修改原因')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
                'ordering': ['-test_date', 'material_batch'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('modification_reason', models.TextField(verbose_name='修改原因')),
                ('modified_data', models.JSONField(default=dict, verbose_name='修改数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_materials.rawmaterial', verbose_name='原料')),
            ],
            options={
                'verbose_name': '原料修改历史',
                'verbose_name_plural': '原料修改历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='原料名称')),
                ('test_item', models.CharField(choices=[('appearance', '外观'), ('purity', '纯度'), ('peak_position', '出峰位置'), ('inhibitor_content', '阻聚剂含量'), ('moisture_content', '水分含量'), ('color', '色度'), ('ethanol_content', '乙醇含量'), ('acidity', '酸度')], max_length=50, verbose_name='检测项目')),
                ('standard_type', models.CharField(choices=[('external_control', '外控标准'), ('internal_control', '内控标准'), ('supplier_standard', '供应商标准')], max_length=20, verbose_name='标准类型')),
                ('lower_limit', models.FloatField(blank=True, null=True, verbose_name='下限')),
                ('upper_limit', models.FloatField(blank=True, null=True, verbose_name='上限')),
                ('target_value', models.FloatField(blank=True, null=True, verbose_name='目标值')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='供应商')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('modified_by', models.CharField(blank=True, max_length=50, verbose_name='修改人')),
                ('modification_reason', models.TextField(blank=True, verbose_name='修改原因')),
            ],
            options={
                'verbose_name': '原料标准',
                'verbose_name_plural': '原料标准',
                'unique_together': {('material_name', 'test_item', 'standard_type', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='RawMaterialStandardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('modification_reason', models.TextField(verbose_name='修改原因')),
                ('modified_data', models.JSONField(default=dict, verbose_name='修改数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('raw_material_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_materials.rawmaterialstandard', verbose_name='原料标准')),
            ],
            options={
                'verbose_name': '原料标准修改历史',
                'verbose_name_plural': '原料标准修改历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
