# Generated by Django 5.2.5 on 2025-08-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='sample_category',
            field=models.CharField(choices=[('来料', '来料'), ('送样', '送样')], max_length=50, verbose_name='样品类别'),
        ),
    ]
