# Generated by Django 5.2.5 on 2025-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_alter_rawmaterial_sample_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_batch',
            field=models.CharField(max_length=50, verbose_name='原料批号'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('material_name', 'material_batch')},
        ),
    ]
