# Generated by Django 5.2.5 on 2025-08-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0003_alter_rawmaterial_material_batch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('material_name', 'test_date')},
        ),
    ]
