# Generated by Django 5.2.5 on 2025-08-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0004_change_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together=set(),
        ),
    ]
