# Generated by Django 5.2.5 on 2025-08-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_rawmaterialstandardhistory;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_rawmaterialhistory;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_rawmaterialstandard;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS products_rawmaterial;",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
