# Generated by Django 5.2.5 on 2025-08-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dryfilmproduct',
            name='external_final_judgment',
            field=models.CharField(blank=True, max_length=20, verbose_name='外控整体判定'),
        ),
        migrations.AddField(
            model_name='dryfilmproduct',
            name='internal_final_judgment',
            field=models.CharField(blank=True, max_length=20, verbose_name='内控整体判定'),
        ),
        migrations.AddField(
            model_name='dryfilmproduct',
            name='judgment_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='判定详情'),
        ),
        migrations.AddField(
            model_name='dryfilmproduct',
            name='judgment_status',
            field=models.CharField(default='待判定', max_length=20, verbose_name='判定状态'),
        ),
    ]
