# Generated by Django 5.2.5 on 2025-08-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_dryfilmproduct_external_final_judgment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dryfilmproduct',
            name='factory_judgment',
        ),
        migrations.RemoveField(
            model_name='dryfilmproduct',
            name='internal_control_judgment',
        ),
    ]
