# Generated by Django 5.2.5 on 2025-08-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_rawmaterial_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstandard',
            name='analysis_method',
            field=models.CharField(blank=True, max_length=200, verbose_name='分析方法/标准'),
        ),
        migrations.AddField(
            model_name='productstandard',
            name='test_condition',
            field=models.CharField(blank=True, max_length=200, verbose_name='检测条件'),
        ),
        migrations.AddField(
            model_name='productstandard',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='单位'),
        ),
    ]
