# Generated by Django 5.2.5 on 2025-08-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_dryfilmproduct_factory_judgment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstandard',
            name='modification_reason',
            field=models.TextField(blank=True, verbose_name='修改原因'),
        ),
        migrations.AddField(
            model_name='productstandard',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, verbose_name='修改人'),
        ),
    ]
