# Generated by Django 5.2.5 on 2025-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productstandard_analysis_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstandard',
            name='text_standard',
            field=models.TextField(blank=True, verbose_name='文本标准'),
        ),
    ]
