# Generated by Django 5.2.5 on 2025-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productstandard_text_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstandard',
            name='appearance_standard',
            field=models.TextField(blank=True, verbose_name='外观标准'),
        ),
    ]
