# Generated by Django 5.2.5 on 2025-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productstandard_appearance_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstandard',
            name='target_value',
            field=models.CharField(blank=True, max_length=200, verbose_name='目标值'),
        ),
    ]
