# Generated by Django 5.2.5 on 2025-08-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productstandardhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryFilmProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('modification_reason', models.TextField(verbose_name='修改原因')),
                ('modified_data', models.JSONField(default=dict, verbose_name='修改数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('dryfilm_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dryfilmproduct', verbose_name='干膜产品')),
            ],
            options={
                'verbose_name': '干膜产品修改历史',
                'verbose_name_plural': '干膜产品修改历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
