# Generated by Django 5.2.5 on 2025-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_dryfilmproducthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryfilmproduct',
            name='batch_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='产品批号'),
        ),
    ]
