# Generated by Django 5.2.5 on 2025-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20250828_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstandard',
            name='target_value',
            field=models.FloatField(blank=True, null=True, verbose_name='目标值'),
        ),
    ]
