# Generated by Django 5.2.5 on 2025-08-24 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_dryfilmproduct_batch_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhesiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default='default', max_length=50, verbose_name='产品牌号')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='产品批号')),
                ('production_line', models.CharField(max_length=50, verbose_name='产线')),
                ('physical_inspector', models.CharField(max_length=50, verbose_name='理化检测人')),
                ('tape_inspector', models.CharField(max_length=50, verbose_name='胶带检测人')),
                ('tape_test_date', models.DateField(verbose_name='胶带测试日期')),
                ('physical_test_date', models.DateField(verbose_name='理化测试日期')),
                ('sample_category', models.CharField(max_length=50, verbose_name='样品类别')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('physical_judgment', models.CharField(blank=True, max_length=20, verbose_name='理化性能判定')),
                ('tape_judgment', models.CharField(blank=True, max_length=20, verbose_name='胶带性能判定')),
                ('final_judgment', models.CharField(blank=True, max_length=20, verbose_name='最终判定')),
                ('judgment_status', models.CharField(default='待判定', max_length=20, verbose_name='判定状态')),
                ('judgment_details', models.JSONField(blank=True, default=dict, verbose_name='判定详情')),
                ('appearance', models.CharField(blank=True, max_length=100, verbose_name='外观')),
                ('solid_content', models.FloatField(blank=True, null=True, verbose_name='固含')),
                ('viscosity', models.FloatField(blank=True, null=True, verbose_name='粘度')),
                ('acid_value', models.FloatField(blank=True, null=True, verbose_name='酸值')),
                ('moisture', models.FloatField(blank=True, null=True, verbose_name='水分')),
                ('residual_monomer', models.FloatField(blank=True, null=True, verbose_name='残单')),
                ('weight_avg_molecular_weight', models.FloatField(blank=True, null=True, verbose_name='重均分子量')),
                ('pdi', models.FloatField(blank=True, null=True, verbose_name='PDI')),
                ('color', models.FloatField(blank=True, null=True, verbose_name='色度')),
                ('initial_tack', models.FloatField(blank=True, null=True, verbose_name='初粘')),
                ('peel_strength', models.FloatField(blank=True, null=True, verbose_name='剥离')),
                ('high_temperature_holding', models.FloatField(blank=True, null=True, verbose_name='高温持粘')),
                ('room_temperature_holding', models.FloatField(blank=True, null=True, verbose_name='常温持粘')),
                ('constant_load_peel', models.FloatField(blank=True, null=True, verbose_name='定荷重剥离')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('modified_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('modification_reason', models.TextField(blank=True, verbose_name='修改原因')),
            ],
            options={
                'verbose_name': '胶粘剂产品',
                'verbose_name_plural': '胶粘剂产品',
                'ordering': ['-physical_test_date', 'batch_number'],
            },
        ),
        migrations.AlterField(
            model_name='productstandard',
            name='test_item',
            field=models.CharField(choices=[('appearance', '外观'), ('solid_content', '固含'), ('viscosity', '粘度'), ('acid_value', '酸值'), ('moisture', '水分'), ('residual_monomer', '残单'), ('weight_avg_molecular_weight', '重均分子量'), ('pdi', 'PDI'), ('color', '色度'), ('initial_tack', '初粘'), ('peel_strength', '剥离'), ('high_temperature_holding', '高温持粘'), ('room_temperature_holding', '常温持粘'), ('constant_load_peel', '定荷重剥离')], max_length=50, verbose_name='检测项目'),
        ),
        migrations.CreateModel(
            name='AdhesiveProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('modification_reason', models.TextField(verbose_name='修改原因')),
                ('modified_data', models.JSONField(default=dict, verbose_name='修改数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('adhesive_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.adhesiveproduct', verbose_name='胶粘剂产品')),
            ],
            options={
                'verbose_name': '胶粘剂产品修改历史',
                'verbose_name_plural': '胶粘剂产品修改历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
