# Generated by Django 5.2.5 on 2025-09-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_target_value_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstandard',
            name='appearance_standard',
        ),
        migrations.AlterField(
            model_name='adhesiveproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='产品牌号'),
        ),
        migrations.AlterField(
            model_name='dryfilmproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='产品牌号'),
        ),
        migrations.AlterField(
            model_name='pilotproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='产品牌号'),
        ),
        migrations.AlterField(
            model_name='productstandard',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='产品牌号'),
        ),
    ]
