# Generated by Django 5.2.5 on 2025-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_dryfilmproduct_dispersion_dryfilmproduct_stability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesiveproduct',
            name='tape_structure',
            field=models.CharField(blank=True, max_length=100, verbose_name='胶带结构'),
        ),
        migrations.AlterField(
            model_name='productstandard',
            name='test_item',
            field=models.CharField(choices=[('appearance', '外观'), ('solid_content', '固含'), ('viscosity', '粘度'), ('acid_value', '酸值'), ('moisture', '水分'), ('residual_monomer', '残单'), ('weight_avg_molecular_weight', '重均分子量'), ('pdi', 'PDI'), ('color', '色度'), ('initial_tack', '初粘'), ('peel_strength', '剥离'), ('high_temperature_holding', '高温持粘'), ('room_temperature_holding', '常温持粘'), ('constant_load_peel', '定荷重剥离'), ('dispersion', '分散性'), ('stability', '稳定性'), ('tape_structure', '胶带结构')], max_length=50, verbose_name='检测项目'),
        ),
    ]
